-- ==========================================
-- DDL & SEED DATA - LITECONVERT HUB
-- ==========================================

CREATE DATABASE IF NOT EXISTS liteconvert;
USE liteconvert;

-- 1. Tools definitions and CMS content
CREATE TABLE IF NOT EXISTS tools (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tool_key VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    page_description TEXT NOT NULL,
    seo_title VARCHAR(255) NOT NULL,
    seo_meta_desc TEXT NOT NULL,
    enabled BOOLEAN DEFAULT 1,
    use_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Tool-specific FAQs (SEO booster)
CREATE TABLE IF NOT EXISTS faqs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tool_id INT NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    sort_order INT DEFAULT 0,
    FOREIGN KEY (tool_id) REFERENCES tools(id) ON DELETE CASCADE
);

-- 3. Administrative access
CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SEED ADMINISTRATIVE ACCOUNT
-- Username: admin
-- Password: admin123 (bcrypt hash)
INSERT INTO admins (username, password_hash)
VALUES ('admin', '$2a$10$XQxIsp.R2P3p2045FmK1kuJ3nQzEaZJ6i0Ue2rOlyJ6c/fP.W/TqS')
ON DUPLICATE KEY UPDATE id=id;

-- SEED 31 POPULAR CONVERTER TOOLS
INSERT INTO tools (tool_key, name, category, page_description, seo_title, seo_meta_desc) VALUES
-- Developer Utilities
('json-yaml', 'JSON to YAML Converter', 'Developer', 
 'Convert your raw JSON data structures into clean, indentation-perfect YAML specifications. This tool helps developers bridge configurations between client-side services and Kubernetes, Ansible, or docker-compose manifests.', 
 'JSON to YAML Converter - Instant Format Converter', 
 'Convert JSON to YAML instantly. High-performance developer tool with syntax validation, dynamic copy-paste, and clean exports.'),
 
('yaml-json', 'YAML to JSON Converter', 'Developer', 
 'Parse and convert complex YAML configurations into valid JSON formatting. Ideal for debuggers, API developers, and parsing YAML files directly in client applications.', 
 'YAML to JSON Converter - Online Formatting Tool', 
 'Transform YAML files to valid JSON instantly. Supports nested lists, complex arrays, and handles multi-document YAML inputs.'),

('json-csv', 'JSON to CSV Converter', 'Developer', 
 'Convert arrays of JSON objects into structured CSV (Comma-Separated Values) spreadsheet tables. Excellent for parsing REST API payloads into Excel or Google Sheets datasets.', 
 'JSON to CSV Converter - JSON Array to Table', 
 'Convert nested or flat JSON datasets into clean CSV formatting. Free spreadsheet parser tool with custom separator settings.'),

('csv-json', 'CSV to JSON Converter', 'Developer', 
 'Parse comma-separated data tables and convert them to clean arrays of JSON objects. Highly useful for databases seeds, data migrations, and formatting Excel sheet exports.', 
 'CSV to JSON Converter - Spreadsheet Data Parser', 
 'Convert tabular CSV lists into clean arrays of JSON objects. Features automatic datatype detection and supports empty rows skip.'),

('xml-json', 'XML to JSON Converter', 'Developer', 
 'Convert structured XML tags, schemas, and attributes into readable JSON files. Supports parsing element nodes, namespace configurations, and child arrays.', 
 'XML to JSON Converter - Translate XML Tags to JSON', 
 'Convert complex XML strings into structured JSON files. Built-in error logging for invalid elements and namespace tags.'),

('json-xml', 'JSON to XML Converter', 'Developer', 
 'Transform JSON structures into clean, nested XML elements. Helpful for developers connecting REST APIs with legacy systems or SOAP endpoints.', 
 'JSON to XML Converter - Convert JSON Data to XML Tags', 
 'Convert JSON files to valid XML schemas. Supports custom root elements, array child nodes, and self-closing tags.'),

('base64', 'Base64 Encoder/Decoder', 'Developer', 
 'Safely encode plain text strings into binary-safe Base64 strings, or decode Base64 codes back into readable text format. Uses standard RFC specifications.', 
 'Base64 Encoder & Decoder - Binary String Codec', 
 'Encode text to Base64 or decode Base64 strings back to normal characters. Online text encoder supporting UTF-8 formats.'),

('url-codec', 'URL Encoder/Decoder', 'Developer', 
 'Convert special characters and spaces inside URLs into percent-encoded formats (%20, etc.) for safe transfer over HTTP protocols, or decode them back to standard characters.', 
 'URL Encoder & Decoder - URL Percent Escape Tool', 
 'Encode query strings or decode percent-encoded URLs. Safe percent-encoding developer utility for query strings.'),

('jwt-decoder', 'JWT Token Decoder', 'Developer', 
 'Parse and verify the contents of JSON Web Tokens (JWT). Decodes headers, payloads, signatures, and dates (issued at, expiration) without sending data to servers.', 
 'JWT Decoder - Decode JSON Web Tokens Online', 
 'Decode JWT tokens locally in your browser. Inspect headers, payload variables, authentication variables, and expiry dates.'),

('hash-generator', 'SHA-256 & MD5 Hash Generator', 'Developer', 
 'Generate cryptographically secure hashes (MD5, SHA-1, SHA-256) locally from plain strings. Ideal for verifying checksums, creating database keys, and passwords salting.', 
 'SHA-256 & MD5 Hash Generator - Online Cryptography tool', 
 'Generate secure SHA-256, SHA-1, or MD5 cryptographic checksum hashes locally. Instant text to cipher tool.'),

('uuid-generator', 'UUID/GUID Generator', 'Developer', 
 'Generate cryptographically random UUID v4 (Universally Unique Identifier) or GUID values. Configure quantity, format options, and copy items instantly.', 
 'UUID Generator - Free GUID v4 Generator Online', 
 'Generate random and unique UUID v4 strings instantly. Ideal for database primary keys, testing, and mock servers.'),

('htaccess-generator', 'Redirect & .htaccess Generator', 'Developer', 
 'Generate server-side Apache .htaccess redirect codes instantly. Setup 301 Permanent Redirects, force HTTPS, block directories index, and block custom user agents.', 
 '.htaccess Redirect Generator - Apache Redirect Setup', 
 'Create valid .htaccess redirect rules. Configure WWW redirects, secure SSL rules, and custom folder password configurations.'),

('cron-generator', 'Cron Job Expression Generator', 'Developer', 
 'Construct and translate crontab schedules using visual builders. Generate cron job expressions and describe schedules in plain English (e.g. Every minute).', 
 'Cron Job Expression Generator - Crontab Scheduler', 
 'Generate cron job schedules using a visual picker. Describes expressions in plain English with syntax validation.'),

-- Designer & CSS Utilities
('hex-rgba', 'HEX to RGBA/HSLA Converter', 'Design', 
 'Convert HEX code formats into RGBA or HSLA codes, including alpha transparency settings. Supports auto-copy and visual color preview panels.', 
 'HEX to RGBA & HSLA Converter - Color Code Translator', 
 'Convert CSS HEX colors to RGBA or HSLA codes. Includes custom opacity ranges and visual palette generators.'),

('rgb-hex', 'RGB to HEX Converter', 'Design', 
 'Convert RGB and RGBA values into hex codes. Highly useful for graphic designers, web designers, and developers formatting color values.', 
 'RGB to HEX Converter - RGB Color Codes to HEX Code', 
 'Convert RGB color channels directly to standard HEX colors. Free color tool with visual picker and responsive display.'),

('color-palette', 'Harmonic Color Palette Generator', 'Design', 
 'Generate harmonic color schemes (Analogous, Monochromatic, Triadic, Tetradic) from a seed color. Export HEX lists for UI/UX projects.', 
 'Color Palette Generator - Harmonic Schemes Creator', 
 'Create professional color schemes from seed values. View, adjust, and copy HEX palettes instantly.'),

('css-gradient', 'CSS Gradient Code Generator', 'Design', 
 'Create linear and radial CSS background gradients visually. Adjust angle controls, insert color stops, preview outputs, and copy CSS values.', 
 'CSS Gradient Generator - Visual Background Gradients', 
 'Create gorgeous linear and radial CSS gradients. Dynamic preview panel with multi-stop color sliders.'),

('svg-optimizer', 'SVG Code Optimizer & Minifier', 'Design', 
 'Optimize vector graphics by minifying raw SVG markup. Removes metadata, editor headers, empty tags, and redundant attributes locally.', 
 'SVG Optimizer - Minify Vector SVG Files Online', 
 'Clean and compress SVG files locally. Reduce vector image size while preserving layouts and paths structure.'),

-- Text & Formatter Utilities
('md-html', 'Markdown to HTML Converter', 'Text', 
 'Convert rich text Markdown files (.md) into valid HTML elements. Supports headings, bold/italics, custom lists, link highlights, and code blocks.', 
 'Markdown to HTML Converter - Rich Text to HTML Code', 
 'Convert Markdown files to clean HTML code. Live visual rendering pane with quick copy utilities.'),

('html-md', 'HTML to Markdown Converter', 'Text', 
 'Transform HTML elements back into clean, text-based Markdown (.md) styling. Cleans tags, nested containers, lists, and links.', 
 'HTML to Markdown Converter - HTML tags to MD markup', 
 'Convert HTML code snippets into clean Markdown format. Cleans inline styles and formatting containers.'),

('case-changer', 'Text Case Changer & Slugify', 'Text', 
 'Transform strings of text into multiple formats: UPPERCASE, lowercase, Title Case, and slug-case (URL friendly slugs).', 
 'Text Case Changer - Slugify & Text Transformer', 
 'Change text case formats instantly. Convert headers to slugs, snake_case, camelCase, or UPPERCASE.'),

('diff-checker', 'Visual Text Diff Checker', 'Text', 
 'Compare two blocks of text and highlight addition, deletion, and modification differences side-by-side or inline in real-time.', 
 'Diff Checker - Compare Text Differences Online', 
 'Compare two documents and highlight word changes. Free text differences tool with inline previews.'),

('lorem-ipsum', 'Lorem Ipsum Text Generator', 'Text', 
 'Generate dummy placeholder text for layouts, mockups, and UI tests. Configure word limits, sentences count, or paragraphs density.', 
 'Lorem Ipsum Generator - Free Placeholder Text Generator', 
 'Generate clean Lorem Ipsum text. Choose between paragraphs, sentences, or lists. Free developer utility.'),

('binary-converter', 'String to Binary & Hex Converter', 'Text', 
 'Convert strings of characters into binary arrays or hexadecimal representations, and translate binary arrays back to standard text.', 
 'String to Binary & Hex Converter - Text to Binary Codec', 
 'Convert plain text to binary string or hexadecimal output. Useful for networking tests and cryptography.'),

-- Math & Unit Utilities
('timestamp-converter', 'Unix Timestamp & Date Converter', 'Math', 
 'Convert Unix epoch timestamps (seconds/milliseconds) into standard UTC and local dates, or translate calendar dates back into epoch time.', 
 'Unix Timestamp Converter - Epoch Date Translator', 
 'Convert Unix timestamps to calendar dates and vice-versa. Supports seconds and milliseconds parsing.'),

('number-converter', 'Binary/Hex Base Converter', 'Math', 
 'Convert integers between multiple base representations: Binary (Base 2), Octal (Base 8), Decimal (Base 10), and Hexadecimal (Base 16).', 
 'Number Base Converter - Binary, Octal, Decimal, Hex', 
 'Convert numbers between binary, octal, decimal, and hexadecimal bases. High performance math base converter.'),

('percentage-calculator', 'Percentage Math Calculator', 'Math', 
 'Compute percentage increases, percentage decreases, differences, or values calculations. Clear forms with instant outputs.', 
 'Percentage Calculator - Percentage Difference & Increase', 
 'Calculate percentage values, percentage increments, discounts, and differences. Simple inputs with instant results.'),

('roman-converter', 'Roman Numerals Converter', 'Math', 
 'Convert decimal integers (1-3999) into Roman Numerals (e.g. MMXVI), or translate Roman Numeral strings back to decimals.', 
 'Roman Numerals Converter - Integer to Roman translator', 
 'Convert decimal integers into Roman numerals and vice-versa. Built-in Roman syntax validator.'),

('px-rem', 'PX to REM Converter', 'Math', 
 'Convert design pixels (px) into relative CSS root em (rem) metrics based on a custom base size (e.g. 16px). Supports interactive scale tables.', 
 'PX to REM Converter - CSS px to rem translator', 
 'Convert pixels to relative rem CSS values. Dynamic grid output with adjustable base font size values.'),

('timezone-converter', 'Timezone Converter & UTC Compare', 'Math', 
 'Compare local times across global timezones. Add zone inputs, select offsets, compare time differences, and verify timezone details.', 
 'Timezone Converter - Global UTC Compare Tool', 
 'Convert times across multiple timezones. Add global zones to compare time differences dynamically.'),

('html-formatter', 'HTML Formatter & Minifier', 'Text', 
 'Beautify or minify HTML code sheets locally. Cleans nested tag alignment and collapses empty attributes.', 
 'HTML Formatter & Minifier - Markup Beautifier', 
 'Format or minify HTML markup. Free local code editor with instant copy and syntax cleanup.');


-- SEED DEFAULT FAQs FOR POPULAR TOOLS
INSERT INTO faqs (tool_id, question, answer, sort_order) VALUES
((SELECT id FROM tools WHERE tool_key = 'json-yaml'), 'What is the main difference between JSON and YAML?', 'JSON is a lightweight data-interchange format based on JavaScript object syntax, designed for machine parsing. YAML is a human-friendly data serialization standard, optimized for readability and widely used in configuration files (like Docker or Kubernetes).', 1),
((SELECT id FROM tools WHERE tool_key = 'json-yaml'), 'Does this JSON to YAML converter send my data to a server?', 'No, all conversion calculations run entirely client-side in your browser. Your data remains fully secure and private on your machine.', 2),
((SELECT id FROM tools WHERE tool_key = 'json-yaml'), 'How does the tool handle syntax errors in JSON?', 'The tool checks your JSON format in real-time. If it finds a syntax error (like a missing comma or quotation mark), it will highlight the line and show an error message so you can fix it.', 3),
((SELECT id FROM tools WHERE tool_key = 'json-yaml'), 'Can I convert nested JSON objects and arrays to YAML?', 'Yes, the converter fully supports deep nested objects, arrays, integers, booleans, and null values, converting them into clean YAML indentation.', 4),
((SELECT id FROM tools WHERE tool_key = 'json-yaml'), 'Is the converted YAML output compliant with YAML standards?', 'Yes, the output uses standard 2-space indentation and valid syntax, ensuring it works in configurations for Kubernetes, Ansible, and Docker.', 5),
((SELECT id FROM tools WHERE tool_key = 'yaml-json'), 'Why convert YAML to JSON?', 'While YAML is easier to write manually, JSON is the standard format for REST APIs and web integrations. Converting YAML to JSON allows you to feed configurations into APIs, webhooks, or JavaScript code.', 1),
((SELECT id FROM tools WHERE tool_key = 'yaml-json'), 'Is my data safe with the online YAML to JSON converter?', 'Absolutely. The conversion logic runs entirely in your local browser using JavaScript. No data is sent to our servers.', 2),
((SELECT id FROM tools WHERE tool_key = 'yaml-json'), 'Can I parse multiple YAML documents in a single file?', 'Yes, the parser is designed to identify multi-document structures separated by "---" and translate them into a single JSON array structure.', 3),
((SELECT id FROM tools WHERE tool_key = 'yaml-json'), 'What happens if my YAML has tab characters?', 'YAML does not allow tabs for indentation. If your input contains tabs, our validation engine will highlight the tab characters and explain how to fix the spacing.', 4),
((SELECT id FROM tools WHERE tool_key = 'yaml-json'), 'How are YAML comments handled?', 'JSON does not support comments. Any comments starting with "#" in your YAML will be removed during conversion.', 5),
((SELECT id FROM tools WHERE tool_key = 'json-csv'), 'How do you translate a nested JSON structure into a flat CSV format?', 'The converter flattens nested objects by joining keys with dots (e.g., "user.name" or "user.address.city") to create standard table columns.', 1),
((SELECT id FROM tools WHERE tool_key = 'json-csv'), 'Is there a file size limit for converting JSON to CSV?', 'The conversion runs in your browser, so the speed depends on your device''s memory. It can easily handle files up to 5MB (thousands of rows) without lag.', 2),
((SELECT id FROM tools WHERE tool_key = 'json-csv'), 'Can I configure the field delimiter?', 'Yes, you can choose between a comma (,), semicolon (;), or tab character to separate values, matching your regional spreadsheet settings.', 3),
((SELECT id FROM tools WHERE tool_key = 'json-csv'), 'How does the tool handle missing values?', 'If a specific key is missing from a JSON object, the corresponding column in that CSV row will be left empty.', 4),
((SELECT id FROM tools WHERE tool_key = 'json-csv'), 'Can I export the CSV output directly to Microsoft Excel?', 'Yes, you can download the generated output as a .csv file, which can be opened directly in Microsoft Excel, Google Sheets, or Numbers.', 5),
((SELECT id FROM tools WHERE tool_key = 'csv-json'), 'What format of JSON is produced from the CSV?', 'The tool generates a JSON array of objects, where the first row of your CSV is parsed as keys (header row) and subsequent rows are values.', 1),
((SELECT id FROM tools WHERE tool_key = 'csv-json'), 'How does the tool handle numeric values and booleans in CSV?', 'It detects numeric values, booleans, and nulls, converting them to their correct JSON types instead of wrapping everything in string quotes.', 2),
((SELECT id FROM tools WHERE tool_key = 'csv-json'), 'Can I convert CSV strings that contain commas inside quotes?', 'Yes, the parser conforms to RFC 4180 standards and correctly handles field values containing commas wrapped in double quotes.', 3),
((SELECT id FROM tools WHERE tool_key = 'csv-json'), 'What separator characters are supported?', 'It automatically detects commas, semicolons, tabs (\t), and pipes (|) as field separators.', 4),
((SELECT id FROM tools WHERE tool_key = 'csv-json'), 'Does the converter support line breaks inside fields?', 'Yes, multiline fields enclosed in double quotes are correctly parsed into single string values in the JSON output.', 5),
((SELECT id FROM tools WHERE tool_key = 'xml-json'), 'How are XML attributes parsed into JSON?', 'XML attributes are parsed into JSON keys prefixed with "@" or grouped inside an attributes property, keeping them separate from child elements.', 1),
((SELECT id FROM tools WHERE tool_key = 'xml-json'), 'How does the converter handle XML namespaces?', 'Namespaces are preserved by retaining their prefix in the JSON keys (e.g., "soap:Envelope"), ensuring no mapping information is lost.', 2),
((SELECT id FROM tools WHERE tool_key = 'xml-json'), 'What happens if an XML tag is repeated multiple times?', 'Repeated child elements with the same tag name are grouped together into a JSON array, representing the node collection.', 3),
((SELECT id FROM tools WHERE tool_key = 'xml-json'), 'Is my XML data secure when using this tool?', 'Yes, all XML parsing and formatting are executed locally using client-side JavaScript. Your data never leaves your computer.', 4),
((SELECT id FROM tools WHERE tool_key = 'xml-json'), 'Can I convert self-closing XML tags?', 'Yes, self-closing tags are parsed as null values or empty objects in the final JSON layout.', 5),
((SELECT id FROM tools WHERE tool_key = 'json-xml'), 'Why convert JSON to XML?', 'XML is still standard in enterprise services, SOAP APIs, and legacy banking systems. Converting JSON to XML helps modern apps integrate with these systems.', 1),
((SELECT id FROM tools WHERE tool_key = 'json-xml'), 'What is the root element name in the generated XML?', 'By default, the tool wraps the elements in a "<root>" tag, but you can configure the custom root element name in the tool settings.', 2),
((SELECT id FROM tools WHERE tool_key = 'json-xml'), 'How are arrays represented in the output XML?', 'Array items are rendered as repeated elements with the parent element''s key as the tag name.', 3),
((SELECT id FROM tools WHERE tool_key = 'json-xml'), 'Does the tool support converting JSON keys with spaces?', 'XML tag names cannot contain spaces. The converter automatically replaces spaces in JSON keys with hyphens or underscores to keep it valid.', 4),
((SELECT id FROM tools WHERE tool_key = 'json-xml'), 'Can I add attributes to the XML tags?', 'Yes, keys prefixed with "@" in your JSON input will be rendered as attributes on their parent element tag.', 5),
((SELECT id FROM tools WHERE tool_key = 'base64'), 'What is Base64 encoding used for?', 'Base64 is used to encode binary data (like images or files) into a safe ASCII string format, allowing it to be sent over text-only protocols like SMTP, HTML, or JSON.', 1),
((SELECT id FROM tools WHERE tool_key = 'base64'), 'Is Base64 encoding a form of encryption?', 'No, Base64 is not encryption. It is a data format encoding method. Anyone can easily decode a Base64 string back to its original form, so never use it for passwords.', 2),
((SELECT id FROM tools WHERE tool_key = 'base64'), 'Can I encode files or images to Base64?', 'Yes, our tool supports both text-to-Base64 encoding and decoding, as well as file uploads to generate Base64 data URLs.', 3),
((SELECT id FROM tools WHERE tool_key = 'base64'), 'Does Base64 increase file size?', 'Yes, Base64 encoding increases the data size by approximately 33% because it represents binary data using 6 bits per character instead of 8.', 4),
((SELECT id FROM tools WHERE tool_key = 'base64'), 'Does this tool support UTF-8 characters?', 'Yes, the encoder uses UTF-8 byte conversion, ensuring special characters and emojis are encoded and decoded correctly without breaking.', 5),
((SELECT id FROM tools WHERE tool_key = 'url-codec'), 'What is URL percent-encoding?', 'URL encoding replaces unsafe characters in query parameters with a "%" followed by their hexadecimal code (e.g., spaces become "%20"), ensuring URLs parse correctly in browsers.', 1),
((SELECT id FROM tools WHERE tool_key = 'url-codec'), 'When should I URL encode text?', 'You should encode any data passed in URL query parameters, especially special characters (?, &, =, #) or foreign language characters.', 2),
((SELECT id FROM tools WHERE tool_key = 'url-codec'), 'Is URL encoding secure?', 'No, it is simply a format translation for browser compatibility. It does not provide any security or encryption.', 3),
((SELECT id FROM tools WHERE tool_key = 'url-codec'), 'What is the difference between encodeURI and encodeURIComponent?', 'encodeURI leaves domain characters like `:`, `/`, and `?` alone to keep the URL functional. encodeURIComponent escapes all characters, which is necessary when nesting a URL inside another query parameter.', 4),
((SELECT id FROM tools WHERE tool_key = 'url-codec'), 'Does this tool decode space characters as "+" or "%20"?', 'The decoder handles both formats, translating both "%20" and the legacy query "+" back to standard space characters.', 5),
((SELECT id FROM tools WHERE tool_key = 'jwt-decoder'), 'What are the three parts of a JSON Web Token (JWT)?', 'A JWT contains three parts separated by dots: the Header (specifies algorithm), Payload (contains user claims/data), and Signature (verifies integrity).', 1),
((SELECT id FROM tools WHERE tool_key = 'jwt-decoder'), 'Does decoding a JWT expose my security keys?', 'No, our JWT decoder decodes only the Base64-encoded Header and Payload locally in your browser. It does not send data online or verify signature keys on external servers.', 2),
((SELECT id FROM tools WHERE tool_key = 'jwt-decoder'), 'Can this tool verify if a JWT is expired?', 'Yes, the tool parses the "exp" (expiration time) and "iat" (issued at) claims, compares them with the current time, and displays whether the token is still valid.', 3),
((SELECT id FROM tools WHERE tool_key = 'jwt-decoder'), 'Can I edit a JWT payload and resign it with this tool?', 'This tool is a decoder for debugging and analysis. It does not sign tokens, as signing requires a private key which should never be entered on a public website.', 4),
((SELECT id FROM tools WHERE tool_key = 'jwt-decoder'), 'Why is my decoded JWT payload showing raw Unix timestamps?', 'JWT specifications use Unix epoch timestamps (in seconds) for dates. The tool automatically displays the human-readable date right next to these values.', 5),
((SELECT id FROM tools WHERE tool_key = 'hash-generator'), 'What is a cryptographic hash?', 'A hash is a one-way mathematical function that converts text of any length into a fixed-length string of characters. It is impossible to reverse-engineer the original text from the hash.', 1),
((SELECT id FROM tools WHERE tool_key = 'hash-generator'), 'What is the difference between MD5 and SHA-256?', 'MD5 produces a 128-bit hash and is faster but vulnerable to collision attacks (not secure for passwords). SHA-256 produces a secure 256-bit hash, widely used in cryptography and block-chains.', 2),
((SELECT id FROM tools WHERE tool_key = 'hash-generator'), 'Does this hash generator store my text?', 'No, all hashing calculations are performed client-side using JavaScript libraries. Your text is never sent to our servers.', 3),
((SELECT id FROM tools WHERE tool_key = 'hash-generator'), 'Why does the same input text always generate the exact same hash?', 'Hashing functions are deterministic. The same input will always yield the same output. Even changing a single character will completely change the resulting hash.', 4),
((SELECT id FROM tools WHERE tool_key = 'hash-generator'), 'Can I check if a file checksum matches a hash using this tool?', 'Yes, you can generate the checksum hash of your text or file content and compare it with the manufacturer''s hash to verify file integrity.', 5),
((SELECT id FROM tools WHERE tool_key = 'uuid-generator'), 'What is a UUID?', 'Universally Unique Identifier, a 128-bit number used to identify information without a central registration authority.', 1),
((SELECT id FROM tools WHERE tool_key = 'uuid-generator'), 'What is the difference between UUID version 4 and others?', 'Version 4 is generated using cryptographically strong random numbers, whereas version 1 uses MAC addresses and timestamps.', 2),
((SELECT id FROM tools WHERE tool_key = 'uuid-generator'), 'Is a UUID version 4 guaranteed to be unique?', 'Yes, practically. The probability of a duplicate is so small that it is statistically zero.', 3),
((SELECT id FROM tools WHERE tool_key = 'uuid-generator'), 'Can I use these generated UUIDs for commercial database keys?', 'Yes, they conform to RFC 4122 specifications and are production-ready.', 4),
((SELECT id FROM tools WHERE tool_key = 'uuid-generator'), 'Does the tool run online or offline?', 'It runs fully local in your browser. No UUIDs are generated on the server or logged.', 5),
((SELECT id FROM tools WHERE tool_key = 'htaccess-generator'), 'What is a .htaccess file?', 'A configuration file used on Apache web servers to control directory-level configurations like redirection, security, and cache settings.', 1),
((SELECT id FROM tools WHERE tool_key = 'htaccess-generator'), 'How do I create a .htaccess file on Windows?', 'Windows doesn''t allow names starting with a dot easily. Save it as htaccess.txt first, upload it to the server, and rename it to .htaccess there.', 2),
((SELECT id FROM tools WHERE tool_key = 'htaccess-generator'), 'What is a 301 redirect?', 'A permanent redirect that transfers 90-99% of search engine ranking power to the new redirected URL.', 3),
((SELECT id FROM tools WHERE tool_key = 'htaccess-generator'), 'How do I force HTTPS redirects?', 'The generator includes a checkbox to add rules that redirect all HTTP traffic to secure HTTPS.', 4),
((SELECT id FROM tools WHERE tool_key = 'htaccess-generator'), 'Will these rules break my server if configured incorrectly?', 'Yes, invalid .htaccess syntax will cause a 500 Internal Server Error. Always back up your current .htaccess file before uploading a new one.', 5),
((SELECT id FROM tools WHERE tool_key = 'cron-generator'), 'What is a cron expression?', 'A string of five or six fields representing a schedule to trigger automated scripts/jobs on Linux/Unix systems.', 1),
((SELECT id FROM tools WHERE tool_key = 'cron-generator'), 'How do I read a cron schedule?', 'From left to right: minute, hour, day of month, month, day of week.', 2),
((SELECT id FROM tools WHERE tool_key = 'cron-generator'), 'What does the asterisk (*) symbol mean in cron?', 'It means "every", so * in the minute field means run every minute.', 3),
((SELECT id FROM tools WHERE tool_key = 'cron-generator'), 'What is the difference between Unix cron and Quartz cron?', 'Unix cron uses five fields and minute-level precision; Quartz cron uses six or seven fields and supports second-level triggers.', 4),
((SELECT id FROM tools WHERE tool_key = 'cron-generator'), 'Can I run a cron job every 5 minutes?', 'Yes, you configure it as "*/5 * * * *" which is fully supported by our visual builder.', 5),
((SELECT id FROM tools WHERE tool_key = 'hex-rgba'), 'What does RGBA stand for?', 'Red, Green, Blue, Alpha. Alpha represents color opacity/transparency ranging from 0 to 1.', 1),
((SELECT id FROM tools WHERE tool_key = 'hex-rgba'), 'What is HSLA color?', 'Hue, Saturation, Lightness, Alpha. Often preferred by designers as it makes color variations easier to predict.', 2),
((SELECT id FROM tools WHERE tool_key = 'hex-rgba'), 'How do I convert a 3-character HEX to RGBA?', 'The tool expands 3-character HEX codes like "#F00" to "#FF0000" before translating.', 3),
((SELECT id FROM tools WHERE tool_key = 'hex-rgba'), 'Does the converter support 8-character HEX codes?', 'Yes, 8-character HEX codes include transparency, which the tool parses directly to RGBA/HSLA.', 4),
((SELECT id FROM tools WHERE tool_key = 'hex-rgba'), 'Can I preview the transparency visually?', 'Yes, the preview card displays a checkerboard background to visualize the alpha opacity.', 5),
((SELECT id FROM tools WHERE tool_key = 'rgb-hex'), 'What is RGB format?', 'Red, Green, Blue color channels, each ranging from 0 to 255.', 1),
((SELECT id FROM tools WHERE tool_key = 'rgb-hex'), 'What is a HEX color code?', 'A hexadecimal representation of RGB values, starting with a "#" and using base-16 notation.', 2),
((SELECT id FROM tools WHERE tool_key = 'rgb-hex'), 'How are RGBA colors with opacity converted to HEX?', 'They are converted into 8-character HEX codes where the last two characters represent alpha opacity.', 3),
((SELECT id FROM tools WHERE tool_key = 'rgb-hex'), 'Is color conversion lossless?', 'Yes, RGB and HEX map the exact same color space, so converting between them is perfectly lossless.', 4),
((SELECT id FROM tools WHERE tool_key = 'rgb-hex'), 'Can I copy the HEX code with or without the hash (#) symbol?', 'Yes, the converter provides copy options for both styles.', 5),
((SELECT id FROM tools WHERE tool_key = 'color-palette'), 'What is an analogous color palette?', 'Three colors side-by-side on the 360-degree color wheel, creating a calm, cohesive design.', 1),
((SELECT id FROM tools WHERE tool_key = 'color-palette'), 'What is a triadic color scheme?', 'Three colors evenly spaced around the color wheel, offering high contrast while staying balanced.', 2),
((SELECT id FROM tools WHERE tool_key = 'color-palette'), 'How does monochromatic generation work?', 'It takes a base hue and changes the saturation and lightness to build a consistent single-color palette.', 3),
((SELECT id FROM tools WHERE tool_key = 'color-palette'), 'How do I export my palette?', 'You can copy individual HEX codes, or copy the entire palette array to use in CSS/SCSS.', 4),
((SELECT id FROM tools WHERE tool_key = 'color-palette'), 'Can I lock the base color?', 'Yes, you can pick a base color and generate different palettes dynamically without changing the base.', 5),
((SELECT id FROM tools WHERE tool_key = 'css-gradient'), 'What is the difference between linear and radial gradients?', 'Linear gradients blend colors along a straight line; radial gradients blend colors outward from a central point.', 1),
((SELECT id FROM tools WHERE tool_key = 'css-gradient'), 'How do color stops work in CSS gradients?', 'Color stops define where specific colors start and end, with the browser interpolating the colors between them.', 2),
((SELECT id FROM tools WHERE tool_key = 'css-gradient'), 'Is the generated CSS code cross-browser compatible?', 'Yes, the output uses modern standard CSS background-image properties supported by all modern browsers.', 3),
((SELECT id FROM tools WHERE tool_key = 'css-gradient'), 'Can I add transparency to gradient stops?', 'Yes, the color picker supports RGBA opacity, allowing you to create beautiful transparent gradients.', 4),
((SELECT id FROM tools WHERE tool_key = 'css-gradient'), 'How do I change the angle of a linear gradient?', 'Use the circular angle selector to rotate the gradient path in real-time.', 5),
((SELECT id FROM tools WHERE tool_key = 'svg-optimizer'), 'Why should I optimize SVG files?', 'SVG vector graphics often contain metadata from editors like Illustrator/Inkscape. Minifying SVGs reduces page load times.', 1),
((SELECT id FROM tools WHERE tool_key = 'svg-optimizer'), 'Is SVG optimization lossy?', 'Usually lossless. It removes metadata, comments, and empty groups, but keeps coordinate precisions unchanged.', 2),
((SELECT id FROM tools WHERE tool_key = 'svg-optimizer'), 'Does this optimizer upload my SVGs online?', 'No, all processing is done locally in your browser. Your design files are secure.', 3),
((SELECT id FROM tools WHERE tool_key = 'svg-optimizer'), 'Can I reduce coordinate precision to shrink file size?', 'Yes, reducing path decimal precision significantly decreases file size for complex SVG vectors.', 4),
((SELECT id FROM tools WHERE tool_key = 'svg-optimizer'), 'What is raw SVG code?', 'It is XML-based text representing shapes, lines, and curves, which can be modified directly.', 5),
((SELECT id FROM tools WHERE tool_key = 'md-html'), 'What is Markdown?', 'A lightweight markup language with plain-text-formatting syntax that can be converted to HTML.', 1),
((SELECT id FROM tools WHERE tool_key = 'md-html'), 'Does the converter support code syntax highlighting?', 'Yes, it formats code blocks using standard pre/code HTML wrappers.', 2),
((SELECT id FROM tools WHERE tool_key = 'md-html'), 'Can I write inline HTML tags inside my Markdown?', 'Yes, the parser supports inline HTML tags without breaking the layout.', 3),
((SELECT id FROM tools WHERE tool_key = 'md-html'), 'How are links and images rendered?', 'Standard Markdown [link](url) and ![alt](url) elements are converted to standard <a> and <img> tags.', 4),
((SELECT id FROM tools WHERE tool_key = 'md-html'), 'Does this tool validate HTML outputs?', 'Yes, it ensures all generated tags close correctly, keeping your page layouts intact.', 5),
((SELECT id FROM tools WHERE tool_key = 'html-md'), 'When should I convert HTML to Markdown?', 'When migrating content from a CMS to static site generators like Jekyll, Hugo, or Gatsby.', 1),
((SELECT id FROM tools WHERE tool_key = 'html-md'), 'Does the converter preserve CSS classes and IDs?', 'No, Markdown does not support classes or IDs, so standard tags are simplified to markdown formatting.', 2),
((SELECT id FROM tools WHERE tool_key = 'html-md'), 'Can it convert nested HTML tables?', 'Tables are translated into standard Markdown pipe table format if simple, or left as inline HTML for complex tables.', 3),
((SELECT id FROM tools WHERE tool_key = 'html-md'), 'Are javascript tags removed?', 'Yes, scripts, styles, and headers are stripped out to keep the Markdown clean.', 4),
((SELECT id FROM tools WHERE tool_key = 'html-md'), 'How are HTML blockquotes handled?', 'They are translated to markdown standard ">" quote indicators.', 5),
((SELECT id FROM tools WHERE tool_key = 'case-changer'), 'What is slugify?', 'Converting a string into a URL-friendly format: lowercase, alphanumeric characters, and dashes instead of spaces.', 1),
((SELECT id FROM tools WHERE tool_key = 'case-changer'), 'What is camelCase?', 'Formatting text where spaces are removed and each word starts with a capital letter, except the first one.', 2),
((SELECT id FROM tools WHERE tool_key = 'case-changer'), 'What is snake_case?', 'Formatting text with all lowercase letters and words separated by underscores.', 3),
((SELECT id FROM tools WHERE tool_key = 'case-changer'), 'Can I restore my text to its original casing after conversion?', 'No, casing changes are destructive. Keep a backup copy of your original text.', 4),
((SELECT id FROM tools WHERE tool_key = 'case-changer'), 'Does this case changer support special accents and characters?', 'Yes, slugify transliterates accented characters to standard ASCII.', 5),
((SELECT id FROM tools WHERE tool_key = 'diff-checker'), 'What is a diff checker?', 'A utility that compares two versions of a document and highlights additions, deletions, and updates.', 1),
((SELECT id FROM tools WHERE tool_key = 'diff-checker'), 'What is the difference between inline and split view?', 'Split view shows original and updated text side-by-side; inline view shows them in a single stream with red/green highlights.', 2),
((SELECT id FROM tools WHERE tool_key = 'diff-checker'), 'Does the tool compare characters or entire words?', 'It supports word-by-word comparison for general text and line-by-line checks for code.', 3),
((SELECT id FROM tools WHERE tool_key = 'diff-checker'), 'Is my text private when using this tool?', 'Yes, all comparison calculations are run locally in the browser.', 4),
((SELECT id FROM tools WHERE tool_key = 'diff-checker'), 'Can I compare code files using this diff checker?', 'Yes, it is excellent for comparing code modifications, JSON objects, or plain text.', 5),
((SELECT id FROM tools WHERE tool_key = 'lorem-ipsum'), 'What is Lorem Ipsum?', 'Dummy placeholder text used in layouts and typesetting to fill spaces before the actual copy is ready.', 1),
((SELECT id FROM tools WHERE tool_key = 'lorem-ipsum'), 'What is the origin of Lorem Ipsum?', 'It originates from a passage of Cicero''s work written in 45 BC.', 2),
((SELECT id FROM tools WHERE tool_key = 'lorem-ipsum'), 'Can I generate HTML paragraphs?', 'Yes, the tool has options to wrap text paragraphs in standard <p> tags for easy copying.', 3),
((SELECT id FROM tools WHERE tool_key = 'lorem-ipsum'), 'How is this placeholder text structured?', 'You can choose the count of words, sentences, or full paragraphs to fit your layout template.', 4),
((SELECT id FROM tools WHERE tool_key = 'lorem-ipsum'), 'Is it free to use for commercial projects?', 'Yes, Lorem Ipsum is public domain and free to use in any design.', 5),
((SELECT id FROM tools WHERE tool_key = 'binary-converter'), 'How does string to binary conversion work?', 'It parses the UTF-8 charCode of each character and converts it into its 8-bit binary equivalent.', 1),
((SELECT id FROM tools WHERE tool_key = 'binary-converter'), 'What is the hexadecimal representation of a string?', 'It is the base-16 conversion of character byte values, often used in debuggers.', 2),
((SELECT id FROM tools WHERE tool_key = 'binary-converter'), 'Can I convert binary code back to readable text?', 'Yes, paste binary data separated by spaces, and the tool decodes it back to text.', 3),
((SELECT id FROM tools WHERE tool_key = 'binary-converter'), 'Does the converter support emojis?', 'Yes, it supports multi-byte Unicode characters, including emojis and foreign characters.', 4),
((SELECT id FROM tools WHERE tool_key = 'binary-converter'), 'Why is my binary output separated by spaces?', 'Spacing every 8 bits makes it easier to read and debug byte arrays.', 5),
((SELECT id FROM tools WHERE tool_key = 'html-formatter'), 'What is the difference between formatting and minifying HTML?', 'Formatting adds indentation and line breaks for readability; minifying removes spacing and comments to reduce file size.', 1),
((SELECT id FROM tools WHERE tool_key = 'html-formatter'), 'Does minifying HTML speed up my website?', 'Yes, removing unnecessary whitespace reduces page file size, lowering load times.', 2),
((SELECT id FROM tools WHERE tool_key = 'html-formatter'), 'Does the minifier break inline JavaScript or CSS?', 'The minifier preserves valid script and style tags, keeping your code fully functional.', 3),
((SELECT id FROM tools WHERE tool_key = 'html-formatter'), 'Can I configure the indentation size?', 'Yes, choose between 2-space, 4-space, or tab layouts for code formatting.', 4),
((SELECT id FROM tools WHERE tool_key = 'html-formatter'), 'Does this tool fix invalid HTML tags?', 'It cleans up structure, but it is not an validation engine. Ensure your tag nesting is valid.', 5),
((SELECT id FROM tools WHERE tool_key = 'timestamp-converter'), 'What is a Unix timestamp?', 'The number of seconds or milliseconds that have elapsed since midnight on January 1, 1970 UTC.', 1),
((SELECT id FROM tools WHERE tool_key = 'timestamp-converter'), 'How do I convert milliseconds to seconds in Unix time?', 'Unix time is in seconds. Divide the millisecond value by 1000.', 2),
((SELECT id FROM tools WHERE tool_key = 'timestamp-converter'), 'Does this converter support timezone conversions?', 'Yes, it displays the output in your local system timezone and UTC simultaneously.', 3),
((SELECT id FROM tools WHERE tool_key = 'timestamp-converter'), 'What is the maximum date value supported by 32-bit Unix time?', 'The year 2038, where a 32-bit signed integer will overflow. This tool uses 64-bit float numbers.', 4),
((SELECT id FROM tools WHERE tool_key = 'timestamp-converter'), 'Can I get the current Unix timestamp instantly?', 'Yes, the page displays the real-time ticking Unix time with a quick copy button.', 5),
((SELECT id FROM tools WHERE tool_key = 'number-converter'), 'What is base conversion?', 'Converting a numeric value between different base representations, such as base-2, base-8, base-10, and base-16.', 1),
((SELECT id FROM tools WHERE tool_key = 'number-converter'), 'What are the base values for Binary, Octal, Decimal, and Hexadecimal?', 'Binary is base-2, Octal is base-8, Decimal is base-10, Hexadecimal is base-16.', 2),
((SELECT id FROM tools WHERE tool_key = 'number-converter'), 'What characters are used in Hexadecimal?', 'The digits 0-9 and letters A-F to represent values from 10 to 15.', 3),
((SELECT id FROM tools WHERE tool_key = 'number-converter'), 'Can I convert floating-point decimal numbers to binary?', 'This base converter is designed for integers. Fractional numbers are rounded.', 4),
((SELECT id FROM tools WHERE tool_key = 'number-converter'), 'Is there a limit to the size of numbers I can convert?', 'It supports up to standard JavaScript safe integer limits, which is 9 quadrillion.', 5),
((SELECT id FROM tools WHERE tool_key = 'percentage-calculator'), 'What formula is used to calculate percentage difference?', 'The absolute difference between two numbers divided by their average, multiplied by 100.', 1),
((SELECT id FROM tools WHERE tool_key = 'percentage-calculator'), 'How do I find a discount price with this tool?', 'Enter the original price and the discount percentage to get the final price and amount saved.', 2),
((SELECT id FROM tools WHERE tool_key = 'percentage-calculator'), 'What is percentage markup?', 'The ratio of profit to the cost price, expressed as a percentage.', 3),
((SELECT id FROM tools WHERE tool_key = 'percentage-calculator'), 'Can this calculator handle negative values?', 'Yes, it supports negative percentage values for calculations.', 4),
((SELECT id FROM tools WHERE tool_key = 'percentage-calculator'), 'Are calculation outputs rounded?', 'Yes, outputs are formatted to 2 decimal places for standard currency and clarity.', 5),
((SELECT id FROM tools WHERE tool_key = 'roman-converter'), 'What is the roman numeral for zero?', 'Ancient Romans did not have a numeral for zero; they used the word "nulla" or "nihil".', 1),
((SELECT id FROM tools WHERE tool_key = 'roman-converter'), 'What is the maximum number I can convert to Roman numerals?', 'The standard Roman system supports up to 3999, as larger values require horizontal bar suffixes.', 2),
((SELECT id FROM tools WHERE tool_key = 'roman-converter'), 'What are the basic Roman numeral characters?', 'I=1, V=5, X=10, L=50, C=100, D=500, M=1000.', 3),
((SELECT id FROM tools WHERE tool_key = 'roman-converter'), 'How do subtraction rules work in Roman numerals?', 'A smaller numeral before a larger one subtracts its value, e.g. IV represents 4, IX represents 9.', 4),
((SELECT id FROM tools WHERE tool_key = 'roman-converter'), 'Does the converter validate Roman numeral syntax?', 'Yes, it validates numeral rules, preventing invalid structures like "IIII" or "VX".', 5),
((SELECT id FROM tools WHERE tool_key = 'px-rem'), 'What is the default base size in web design?', '16 pixels is the standard browser default size, mapping 1rem to 16px.', 1),
((SELECT id FROM tools WHERE tool_key = 'px-rem'), 'Why use REM instead of PX in responsive design?', 'REM scales relative to the browser font settings, which makes designs highly accessible for users with zoomed font settings.', 2),
((SELECT id FROM tools WHERE tool_key = 'px-rem'), 'Can I change the base font size?', 'Yes, input your design base (e.g. 10px or 14px) and the scale table updates immediately.', 3),
((SELECT id FROM tools WHERE tool_key = 'px-rem'), 'Does the converter calculate in both directions?', 'Yes, it translates PX to REM and REM to PX simultaneously.', 4),
((SELECT id FROM tools WHERE tool_key = 'px-rem'), 'Is a scale table generated?', 'Yes, the converter displays a quick-reference scale table showing standard values from 12px to 64px.', 5),
((SELECT id FROM tools WHERE tool_key = 'timezone-converter'), 'What is UTC?', 'Coordinated Universal Time, the primary time standard by which the world regulates clocks.', 1),
((SELECT id FROM tools WHERE tool_key = 'timezone-converter'), 'How do I calculate time difference?', 'By finding the difference between timezone offsets relative to UTC.', 2),
((SELECT id FROM tools WHERE tool_key = 'timezone-converter'), 'Does this converter account for Daylight Saving Time (DST)?', 'Yes, the browser automatically resolves active DST offsets for chosen zones.', 3),
((SELECT id FROM tools WHERE tool_key = 'timezone-converter'), 'Can I compare multiple timezones side-by-side?', 'Yes, add multiple timezone cards to visually align times for virtual meetings.', 4),
((SELECT id FROM tools WHERE tool_key = 'timezone-converter'), 'How do I share a timezone conversion?', 'You can copy the calculated time offset to paste in calendar invites.', 5);
